language: cpp

dist: trusty
sudo: required
os: linux

install:
  - sudo apt-get -qq update
  - export CMAKEVER=3.11.2
  - wget -qO- https://cmake.org/files/v${CMAKEVER/%.[0-9]/}/cmake-${CMAKEVER}-Linux-x86_64.tar.gz | tar xz
  - export PATH="${PWD}/cmake-${CMAKEVER}-Linux-x86_64/bin/:${PATH}"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - valgrind

matrix:
  include:
    - env:
          - MODE=Release
          - BENCHMARK=ON
          - TESTS=OFF
          - COMPILER="g++-7"

    - env:
          - MODE=Release
          - BENCHMARK=ON
          - TESTS=OFF
          - COMPILER="clang++"

    - env:
          - MODE=Debug
          - BENCHMARK=OFF
          - TESTS=ON
          - COMPILER="g++-7"

script:
  - mkdir build/ && cd build/
  - cmake -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=$MODE -D BUILD_TESTING=$TESTS -D BUILD_BENCHMARKS=$BENCHMARK ..
  - make
  - ctest --output-on-failure
  - find benchmarks -type f -executable -exec '{}' \;
